apiVersion: v1
kind: Pod
metadata:
  name: tomcat
  labels:
    estado: "desarrollo"
    responsable: "juan"
spec:
  containers:
   {{ $version := "9.0"}}
   - name: tomcat:{{$version}}
     image: tomcat:{{$version}}