apiVersion: v1
kind: Pod
metadata:
  name: {{.Release.Name }}-nginx1
  labels:
    zone: ejemplo
    version: produccion
  annotations: {
    fecha: tiempo-{{.Release.Time}} ,
    namespace: nombre-{{.Release.Namespace}},
    actualizacion: Actualizacion-{{.Release.IsUpgrade}},
    instalacion: Instalacion-{{.Release.IsInstall}},
    revision: Revision-{{.Release.Revision}}
  }
spec:
  containers:
   - name: nginx   
     image: apasoft/nginx:v1