resources:
- deployment.yaml
- service.yaml

commonLabels:
  app: mywebapp

commonAnnotations:
  app: mykustom-annotations

namePrefix:
  kustom-

nameSuffix:
  -v1

configMapGenerator:
- name: mykustom-map
  env: config.properties