apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name}}-config
  namespace: default
data:
  departamentos: |-
    {{- range $indice,$valor:=.Values.departamentos }}
    - {{ $indice }}: {{$valor}}
    {{- end }}
