apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-init
data:
  init.sh: |
    #!/bin/bash
    set -euo pipefail
    
    echo "[Init] Waiting for local MongoDB to be ready..."
    until /usr/bin/mongo --eval 'db.runCommand({ ping: 1 })' &> /dev/null; do
      echo "[Init] Connecting to local MongoDB..."
      sleep 2
    done
    echo "[Init] Connected to local MongoDB."
    
    HOST="mongo-0.mongo"
    PORT=27017
    REMOTE="$HOST:$PORT"
    
    echo "[Init] Waiting for remote MongoDB (${REMOTE}) to be ready..."
    until /usr/bin/mongo --host "$REMOTE" --eval 'db.runCommand({ ping: 1 })' &> /dev/null; do
      echo "[Init] Connecting to remote MongoDB at $REMOTE..."
      sleep 2
    done
    echo "[Init] Connected to remote MongoDB."
    
    if [[ "$HOSTNAME" != "mongo-0" ]]; then
      echo "[Init] Cloning data from remote ($REMOTE) to local node ($HOSTNAME)..."
      /usr/bin/mongo --host "$REMOTE" --eval 'db.adminCommand({copydb: 1, fromdb: "admin", todb: "'$HOSTNAME'"})'
    else
      echo "[Init] Primary node detected, no copy needed."
    fi
    
    echo "[Init] Initialization complete."