apiVersion: v1
kind: Service
metadata:
  name: node-mongo
  labels:
    app: node-mongo
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30000
  selector:
    app: node-mongo