apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name}}-svc-apache
  labels:
     app: apache
spec:
  {{- if eq .Values.tiposervicio "n"}}
  type: NodePort
  {{ else}}
  type: ClusterIP
  {{ end }}
  ports:
  - port: {{ .Values.puerto }}
    {{- if eq .Values.tiposervicio "n" }}
    nodePort: {{ .Values.nodeport }}
    {{ end }}
    protocol: TCP
  selector:
     app: apache
