apiVersion: v1
kind: Pod
metadata:
  name: {{ .Release.Name }}-tomcat
  labels:
    estado: "desarrollo"
    responsable: "juan"
spec:
  containers:
   - name: tomcat1
     {{- if eq .Values.entorno "desarrollo"}}
     image: tomcat:9.0
     {{ else }}
     image: tomcat:10.0
     {{ end }}
